import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/*
          Canonicalize the host to 127.0.0.1 in the browser. The Supabase
          session cookie is bound to one origin, and the browser treats
          `localhost` and `127.0.0.1` as different domains. The server cannot
          reliably redirect between hosts in dev, so this pre-hydration script
          bounces any `localhost` visit to `127.0.0.1` (same port/path/query)
          before anything renders. No-op on any other host (incl. production).
        */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "if(location.hostname==='localhost'){location.replace(location.href.replace('//localhost','//127.0.0.1'))}",
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
