import { createBrowserClient } from '@supabase/ssr'

/**
 * Supabase client for use in Client Components / browser.
 * Reads the public local-dev env vars generated by `supabase start`.
 */
export function createClient() {
  return createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  )
}
